### ISSUE TITLE
Hover/Preview UX

### ISSUE THREAD

**Issue by dbouwman** [tomwayson/advanced-d-n-d#24]
This would more closely mirror the OpsDash UX...

| action | response |
| --- | --- |
| mouse-over card | show card-controls |
| mouse-over card-controls | highlight card w/ thick outline |
| drag-card over card | show drop-zones & card-proxy |
| drag-card over drop-zone | swap drop-zone icon and show drop-and-split-preview |
| drop-card on drop-zone | move the card |
### Powerpoint UX Design

![slide2](https://cloud.githubusercontent.com/assets/119129/15185960/61fe9882-1758-11e6-83de-1aa438926e24.jpg)

![slide3](https://cloud.githubusercontent.com/assets/119129/15185962/6400bfd4-1758-11e6-8a1d-92cdfc7d7ffc.jpg)

![slide4](https://cloud.githubusercontent.com/assets/119129/15185968/69272318-1758-11e6-92f9-011c697768b4.jpg)

![slide5](https://cloud.githubusercontent.com/assets/119129/15185973/6cbb78b2-1758-11e6-85a1-941389905b18.jpg)

![slide6](https://cloud.githubusercontent.com/assets/119129/15185978/70293a7a-1758-11e6-8a6f-b05192024682.jpg)

![slide7](https://cloud.githubusercontent.com/assets/119129/15185986/77499fc0-1758-11e6-9078-6ec934ca4243.jpg)

![slide8](https://cloud.githubusercontent.com/assets/119129/15185990/7b5afe06-1758-11e6-95f1-f669b9d0e121.jpg)

![slide9](https://cloud.githubusercontent.com/assets/119129/15185994/7eb8ef40-1758-11e6-99f0-041960a83b89.jpg)

**Comment by tomwayson** [comment]
FWIW I like this UX.

I thing showing proxies is something that will work better and in more browsers (IE) than our current solution of showing the actual card (which can have a transparent background and can be hard to see when dragging). No matter what, we should do that.

I _think_ using drop zones will fix some of the UX/jank issues we have now

The only thing that concerns me at all is preview - that seems like it could add complexity, but I'm guessing it's manageable.

**Comment by FelFly** [comment]
Proxies are fine with me. I like the highlight around the active box.

But those indicators for where a row/card is dropping whether on left or right, up and down, are not at all intuitive to me. The drop zone, I don't mind, although I'm still partial to cracks. But the icons are more confusing, they actually look more like a drag handle to me.

"we have the "core" ux we discussed last wk, but I think we can actually replicate more of the OpsDash interactions, which would side-step some minor-yet-irritating-issues we have"

@dbouwman What are the minor-yet-irritating-issues you have?

**Comment by dbouwman** [comment]
@FelFly there is some "disco" style flashing on some drop-zone indicators... this give has low framerate, but they flash ~10/s

![image](http://g.recordit.co/t6DhybnnTI.gif)

**Comment by dbouwman** [comment]
At a meeting on 5/11/16 with @ajturner @astauffer @tomwayson @sidewalkballet it was decided to proceed with the UX described above.

**Comment by tomwayson** [comment]
Now I _want_ the disco
